DROP SEQUENCE PK_HOTEL;
DROP SEQUENCE PK_CLIENTE;
DROP SEQUENCE PK_TIPOQUARTO;
DROP SEQUENCE PK_EMPREGADO;
DROP SEQUENCE PK_SERVICO;

DROP SEQUENCE PK_QUARTO;
DROP SEQUENCE PK_RESERVA;
DROP SEQUENCE PK_ESTADIA;
DROP SEQUENCE PK_SERVICOPRESTADO;