
						
CREATE OR REPLACE FORCE EDITIONABLE VIEW  "QUARTO_HOTEL" ("QUA_IN_NUMERO", "TQU_FK_CODIGO", "HOT_PK_CODHOTEL", "HOT_ST_NOME") AS 
  SELECT 	Q.QUA_PK_NUMERO,
			Q.TQU_FK_CODIGO,
			H.HOT_PK_CODHOTEL,
			H.HOT_ST_NOME
		FROM Quarto Q join Hotel H
				ON Q.HOT_PFK_CODHOTEL = HOT_PK_CODHOTEL;						