create or replace TRIGGER  ADRTRIGGER
BEFORE INSERT OR UPDATE ON ADRRESERVA

FOR EACH ROW
DECLARE 

vid NUMBER;
vTQ number; -- VARIAVEL TIPO DE QUARTO

BEGIN

--VERIFICA TIPO DO QUARTO NA RESERVA
SELECT Q.TQU_IN_CODIGO INTO VTQ
FROM ADRQuarto Q
WHERE Q.QUA_IN_NUMERO = :NEW.QUA_IN_CODQUARTO;

IF VTQ = 1 THEN
    RAISE_APPLICATION_ERROR(-20001,' Quarto não pode ser utilizada cama extra !! ');
END IF;

END;