SELECT 	R.RES_PK_CODIGO AS Codigo,
		TO_CHAR(R.RES_DT_DTCRIA, 'YYYY/MM/DD-HH24:MI') AS DATA_RESERVA,
		R.RES_DT_CHECKIN AS CHECK_IN,
		CASE R.RES_ST_ESTADO WHEN 'C' THEN 'Cancelado'
		ELSE 	CASE R.RES_ST_ESTADO WHEN 'A' THEN 'Anulado'
				ELSE 	CASE R.RES_ST_ESTADO WHEN 'S' THEN 'Confirmado'
						ELSE 'ESPERA' END
				END 
		END AS ESTADO
FROM RESERVA R JOIN Cliente C ON R.cli_fk_codigo = C.cli_pk_codigo;

SELECT 	E.EST_PK_CODIGO AS CODIGO,
		E.HOT_FK_CODIGO AS HOTEL,
		E.QUA_FK_NUMERO AS QUARTO,
		TO_CHAR(E.EST_DT_CHECKIN,'DD/MON/YYYY-HR24:MI') AS CHECK_IN,
		E.RES_FK_CODIGO AS RESERVA
FROM ESTADIA E JOIN Cliente C ON E.CLI_FK_CODIGO = C.CLI_PK_CODIGO;

/*
INSERT INTO RESERVA(qua_fk_numero,hot_fk_codigo,cli_fk_codigo,res_dt_checkin,res_dt_checkout) VALUES (102, 8, 13,TO_DATE('12-DEZ-2017','DD-MON-YYYY'),TO_DATE('15-DEZ-2017','DD-MON-YYYY'));
*/
select * from cliente
select * from QUarto;