CREATE TABLE Hotel(
	hot_pk_codigo NUMBER PRIMARY KEY,
	hot_st_nome VARCHAR2(100 CHAR) NOT NULL,
	hot_st_cnpj VARCHAR2(14 CHAR) NOT NULL,
	hot_st_cidade VARCHAR2(50 CHAR) NOT NULL,
	hot_st_uf VARCHAR2(2 CHAR) NOT NULL,
	hot_st_endereco VARCHAR2(150 CHAR) NOT NULL,
	hot_in_estrelas NUMBER DEFAULT 3
);

CREATE SEQUENCE hot_pk
	START WITH 1
	INCREMENT BY 1
	NOMAXVALUE
	NOCACHE
	NOCYCLE;
	
CREATE OR REPLACE TRIGGER Hotel_pk
BEFORE INSERT ON Hotel
FOR EACH ROW

BEGIN
	SELECT hot_pk.NEXTVAL
	INTO :new.hot_pk_codigo
	FROM DUAL;
END;

/*
DROP TRIGGER Hotel_pk;
DROP SEQUENCE hot_pk;
DROP TABLE Hotel;
*/