/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package clienteban2;

import java.awt.Dimension;
import java.awt.GridLayout;
import java.util.Collections;
import java.util.LinkedHashMap;
import java.util.Map;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JLabel;
import javax.swing.JOptionPane;
import javax.swing.JTextField;

/**
 *
 * @author gustavo
 */
public class JanelaCriar extends javax.swing.JFrame {

    private JanelaPrincipal janelaPrincipal;
    private Tabela tabela;

    private LinkedHashMap<Coluna, JTextField> campos;

    /**
     * Creates new form JanelaCriar
     */
    public JanelaCriar(JanelaPrincipal jp, Tabela tabela) {
        initComponents();
        this.tabela = tabela;
        this.janelaPrincipal = jp;
        this.campos = new LinkedHashMap<>();

        pDados.setLayout(new GridLayout(0, 2));
        jScrollPane1.getVerticalScrollBar()
                .setUnitIncrement(16);

        setupInput();
    }

    private void setupInput() {
        for (int i = 0; i < tabela.getColunas().size(); i++) {

            Coluna coluna = tabela.getColunas().get(i);

            JLabel label = new JLabel(coluna.getNome().toUpperCase() + String.join("", Collections.nCopies(5, " ")) + "( " + coluna.getTipo() + (coluna.isPrimaryKey() ? ", Primary Key " : "") + " ):");
            label.setMaximumSize(new Dimension(Integer.MAX_VALUE, 10));
            label.setMinimumSize(new Dimension(50, 50));
            pDados.add(label);

            JTextField text = new JTextField("");

            //text.setEditable(!coluna.isPrimaryKey());
            text.setMaximumSize(new Dimension(Integer.MAX_VALUE, 10));
            text.setMinimumSize(new Dimension(50, 50));
            pDados.add(text);

            this.campos.put(coluna, text);

            //pDados.add(panel);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        pDados = new javax.swing.JPanel();
        bCria = new javax.swing.JButton();
        bCancela = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        javax.swing.GroupLayout pDadosLayout = new javax.swing.GroupLayout(pDados);
        pDados.setLayout(pDadosLayout);
        pDadosLayout.setHorizontalGroup(
            pDadosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 611, Short.MAX_VALUE)
        );
        pDadosLayout.setVerticalGroup(
            pDadosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 263, Short.MAX_VALUE)
        );

        jScrollPane1.setViewportView(pDados);

        bCria.setText("Criar");
        bCria.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bCriaActionPerformed(evt);
            }
        });

        bCancela.setText("Cancelar");
        bCancela.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bCancelaActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 615, Short.MAX_VALUE)
                .addContainerGap())
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(bCancela)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(bCria))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 267, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(bCria)
                    .addComponent(bCancela))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void bCancelaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bCancelaActionPerformed
        // TODO add your handling code here:
        this.dispose();
    }//GEN-LAST:event_bCancelaActionPerformed

    private void bCriaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bCriaActionPerformed
        // TODO add your handling code here:
        StringBuilder ordem = new StringBuilder();
        StringBuilder valores = new StringBuilder();
        if (tabela.hasInsertionFunction()) {
            valores.append("SELECT ");
            valores.append(tabela.getInsertionFunctionName());
            valores.append('(');

        } else {
            valores.append("INSERT INTO ");
            valores.append(tabela.getName());
            valores.append(" VALUES (");
        }
        boolean isFirst = true;

        for (Map.Entry<Coluna, JTextField> entry : this.campos.entrySet()) {
            Coluna coluna = entry.getKey();
            JTextField text = entry.getValue();

            if (!coluna.isValueValid(text.getText())) {
                JOptionPane.showMessageDialog(this, "Por favor, verifique o campo " + coluna.getNome() + "!", "Valores incorretos", JOptionPane.ERROR_MESSAGE);
                text.requestFocus();
                return;
            }

            //ordem.append(coluna.getNome());
            //ordem.append(",");
            if (!isFirst) {
                valores.append(", ");
            } else {
                isFirst = false;
            }

            if (coluna.getTipo().equals("string")) {
                valores.append('\'');
            }

            valores.append(text.getText());
            
            if (coluna.getTipo().equals("string")) {
                valores.append('\'');
            }

        }
        valores.append(");");
        String toDo = valores.toString();
        System.out.println(toDo);
        try {
            ClienteBan2.getInstance().conexao.RequestChange(toDo);
            JOptionPane.showMessageDialog(this, "Dados inseridos com sucesso!");
            janelaPrincipal.setupTabela();
            this.campos.values().forEach((text) -> {
                text.setText("");
            });
        } catch (Exception ex) {
            Logger.getLogger(JanelaCriar.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_bCriaActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton bCancela;
    private javax.swing.JButton bCria;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JPanel pDados;
    // End of variables declaration//GEN-END:variables
}
